---
# Adding openstack repo 
  - name: Install Openstack Repo
    apt: name=ubuntu-cloud-keyring state=present
  - name: Install Openstack Repo1
    apt_repository: repo='deb http://ubuntu-cloud.archive.canonical.com/ubuntu  trusty-updates/kilo main' state=present
# nava compute packages 
  - name: install packages  
    apt: name={{ item }} state=installed
    with_items:
      - nova-compute
      - sysfsutils
      - neutron-plugin-ml2
      - neutron-plugin-openvswitch-agent
      - ntp

#### NTP SERVER
  - name: ntp configuration
    copy: src=ntp.conf  dest=/etc/ntp.conf backup=yes

  - name: restart ntp
    service: name=ntp state=restarted

  - include: sysctl.yml

  - name: copy nova configuration
    template: src=nova.conf.j2 dest=/etc/nova/nova.conf backup=yes
    notify: nova-compute restart

  - name: copy service restart file 
    copy: src=service.sh dest=/root

  - name: update hypervisor mode
    lineinfile: "dest=/etc/nova/nova-compute.conf state=present regexp='virt_type' line='virt_type = qemu'" 

  - name: copy neutron configuration
    template: src={{ item.name }} dest={{ item.dest}} backup=yes
    with_items:
      - { name: 'neutron.conf.j2' , dest: '/etc/neutron/neutron.conf' }
      - { name: 'ml2_conf.ini.j2' , dest: '/etc/neutron/plugins/ml2/ml2_conf.ini' }
    notify: nova-switch restart
