 service glance-api restart
service glance-registry restart 
service neutron-server restart 
 service nova-api restart
 service nova-cert restart
 service nova-consoleauth restart
 service nova-scheduler restart
 service nova-conductor restart
 service nova-novncproxy restart
