---
- name: configure sysctl
  sysctl: name={{ item.name }} value={{ item.value }} state=present sysctl_file=/etc/sysctl.conf
  with_items:
  - { name: 'net.ipv4.ip_forward' , value: '1' }
  - { name: 'net.ipv4.conf.all.rp_filter' , value: '0' }
  - { name: 'net.ipv4.conf.default.rp_filter' , value: '0' }


